#page title
page_title                                : QuizTempel                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                   # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : QuizTempel                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Kostenlos                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Die ultimative Quiz-App für Wissenshungrige und Quizbegeisterte.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : QuizTempel Team                                
your_link                                 :                     
your_city                                 : Deutschland                                
email_address                             : mappsgsp@hotmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : DDDeal
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Vielfältige Quizfragen
    description                           : Tausende von Fragen aus verschiedenen Wissensgebieten, die dein Wissen auf die Probe stellen.
    fontawesome_icon_name                 : brain
    
  - title                                 : Spielmodi
    description                           : Verschiedene Spielmodi für Einzelspieler und zum Spielen gegen Freunde.
    fontawesome_icon_name                 : gamepad

  - title                                 : Ranglisten
    description                           : Vergleiche deine Ergebnisse mit Freunden und anderen Spielern weltweit.
    fontawesome_icon_name                 : trophy

  - title                                 : Regelmäßige Updates
    description                           : Neue Fragen und Kategorien werden regelmäßig hinzugefügt.
    fontawesome_icon_name                 : sync

  - title                                 : Offline-Modus
    description                           : Spiele auch ohne Internetverbindung deine Lieblingsquizze.
    fontawesome_icon_name                 : wifi-slash
  
  - title                                 : Statistiken
    description                           : Verfolge deinen Fortschritt und erkenne deine Stärken und Schwächen.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Benutzerdefinierte Quizze
    description                           : Erstelle deine eigenen Quizze und teile sie mit Freunden.
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Kategorien
    description                           : Wähle aus verschiedenen Kategorien wie Geschichte, Wissenschaft, Literatur, Sport und viele mehr.
    fontawesome_icon_name                 : folder

  - title                                 : Schwierigkeitsgrade
    description                           : Wähle zwischen verschiedenen Schwierigkeitsgraden, um dein Wissen zu testen.
    fontawesome_icon_name                 : sliders-h



# Theme Settings
topbar_color                              : "#4A148C"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4A148C"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#0D1117"

link_color                                : "#00BCD4"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#3949AB"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#00BCD4"
feature_icons_background_color            : "#301B50"

social_icons_foreground_color             : "#00BCD4"
social_icons_background_color             : "#301B50"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
